name: Deploy to Firebase Hosting on PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Instalação do Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Versão do Flutter

      # Instalação do Firebase CLI
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      # Instalação do FlutterFire CLI
      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      # Configuração do Firebase
      - name: Configure Firebase
        run: flutterfire configure --project=loginflutter-34c6d

      # Verifica e baixa dependências Flutter
      - name: Flutter pub get
        run: flutter pub get

      # Executa os testes do Flutter
      - name: Run Flutter Tests
        run: flutter test

      # Build do projeto (opcional, ajuste se necessário)
      - name: Flutter Build Web
        run: flutter build web

      # Deploy para Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOGINFLUTTER_34C6D }}
          projectId: loginflutter-34c6d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks